### ISSUE TITLE
Move commands under "dtp" parent?

### ISSUE THREAD

**Issue by charlespockert** [DragonTechMC/DTPunishment#29]
Should all commands sit under the main parent e.g.

`/dtp addwords <word1> <word2>`

`/dtp mp add <player_name> <mutepoints>`

Rather than

`/addwords <word1> <word2>`

`/mp add <player_name> <mutepoints>`

It would prevent potential collisions with other plugins

**Comment by yepidoodles** [comment]
Not `/mp` and `/bp`, but all others should

**Comment by charlespockert** [comment]
I'll add the aliases to the config then so you can rename them in case they
clash
