### ISSUE TITLE
Character spam protection for extra characters

### ISSUE THREAD

**Issue by yepidoodles** [DragonTechMC/DTPunishment#32]
Such as @!"£$%^&*( etc

**Comment by charlespockert** [comment]
@yepidoodles wanna elaborate :)

maybe some examples and stuff?

**Comment by yepidoodles** [comment]
`You are awesome!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

**Comment by charlespockert** [comment]
I know, but what did you want to discuss?

**Comment by charlespockert** [comment]
Already done in 60d5df4305566e20d0b0f914d0a51add04e32b81
