### ISSUE TITLE
Error at console

### ISSUE THREAD

**Issue by iLefty** [DragonTechMC/DTPunishment#33]
I don't know, but I have error in console for your plugin:
https://pastebin.com/znd3JSNu
And same error was, when player joined.

**Comment by yepidoodles** [comment]
What Version of Sponge are you using?

**Comment by iLefty** [comment]
> sponge version
[15:41:41] [Server thread/INFO] [nucleus]: Server ran the command: /sponge version
[15:41:41] [Server thread/INFO]: SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a26c654
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2353
    Minecraft Forge: 12.18.3.2272

**Comment by iLefty** [comment]
I noticed a violation of the link to the directory.
/opt/msm/servers/rtest/./config/dtpunishment/data/149658329947742b132b2-8a5f-4e43-ad00-6675ef0354b4.conf.tmp
It should not be:
/./
This is my directory:
/opt/msm/servers/rtest/config/dtpunishment
but no there no folder "data" exist.

**Comment by charlespockert** [comment]
the `/./` is a red herring (it won't make a difference if it's there or not) - I think this is to do with the fact that ninja.configurate won't create a directory automatically when serializing the config the first time - we just need to ensure we push a check/create on any directories that need to be in place when the plugin starts up.

**Comment by charlespockert** [comment]
@LeftBoy @yepidoodles this should be fixed in the latest release 0.9.6

https://github.com/DragonTechMC/DTPunishment/releases/tag/0.9.6
