### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by iLefty** [DragonTechMC/DTPunishment#34]
An excellent plugin, but there is not enough file for translation, by the type messages.conf
I hope that you will add this soon.

**Comment by charlespockert** [comment]
Sounds good - I'll create a language specific version of messages.conf.

It will be easier to have a separate file for each language from a maintenance standpoint.

In the event that we can't find a language the user is currently using on their machine, we will provide a default "fallback" language that the server owner can set in the config. 

We could even provide a command for an user to set a language code for themselves if they are multilingual and can find a language that they understand (or let an admin do this for them)
