### ISSUE TITLE
No to - foul language!

### ISSUE THREAD

**Issue by iLefty** [DragonTechMC/DTPunishment#35]
I propose to replace the forbidden words with symbols, for example on: ******.
If I'm writing a banned word, it will be in the chat room, until I get a ban on writing it.

**Comment by charlespockert** [comment]
@yepidoodles what you think about having this as a config option? Hide bad messages or star bad messages?

**Comment by yepidoodles** [comment]
Yeah, and a config to chose what to replace them with.
