### ISSUE TITLE
Usernames not updating

### ISSUE THREAD

**Issue by yepidoodles** [DragonTechMC/DTPunishment#36]
The first message uses the correct username, but the 2nd one uses the username which the account had when the file was created for that user.

[![https://gyazo.com/cdf3b464a37c8155e64419b4d5f56fbb](https://gyazo.com/cdf3b464a37c8155e64419b4d5f56fbb/raw)](https://gyazo.com/cdf3b464a37c8155e64419b4d5f56fbb)

**Comment by charlespockert** [comment]
Looks like sponge doesn't update the offline user data until someone logs off.

Will do some tweaking and make it look for the online player in all messages before reverting to the offline one.
